# model parameters
resume_gen_temp: 0.3 # chat complete temperature for resume generation
cover_letter_gen_temp: 1.0 # chat completion temperature for cover letter generation
res_count: # number of responsibilities to use per professional experience, starting with the most recent
  - 5
  - 4
  - 3
still_working: True # if True, end date for Enigma will not be given


# formatting parameters

# normal text  formatting
normal_font_name: 'Arial'
normal_font_size: 10
normal_line_spacing: 1.1
normal_font_color:
  - 0
  - 0
  - 0

# header 1 formatting
h1_font_name: 'Arial'
h1_font_size: 12
h1_line_spacing: 1.1
h1_font_color:
  - 23
  - 37
  - 55

# resume specific formatting
resume_image_header: False # if Ture, png header will be used

# cover letter specific formatting
cover_letter_image_header: True # if Ture, png header will be used


# files paths

# input path
cl_content_path: './input/cl_content/' # path to custom cover letter content
pe_input_path: 'input/pe/experience-master.docx' # path to experience docx file
jd_input_path: './input/jd/' # path to job description text file

# intermediate file paths
pe_json_path: './02-intermediate-data/resume_input.json' # path to experience file that has been converted to json
gen_json_path: './02-intermediate-data/' # path to full generated resume json

# output file paths
resume_output_path: './output/jeremy-hatch-' # output for completed and formatted resume
cover_letter_output_path: './output/jeremy-hatch-' # output for completed and formatted cover letter
ad_hoc_response_path: './output/ad_hoc_response.txt' # output for ad hoc response

# Overwrite parameters for job titles if needed
job_title_overrides:
  - 'Senior Data Scientist'
  - 'Data Scientist'
  - 'AI/ML Consultant'